# Generated by Django 3.0.4 on 2020-04-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200417_1852'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
