# Generated by Django 3.0.4 on 2020-03-19 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200318_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='short_description',
            new_name='Specifications',
        ),
    ]
