# Generated by Django 3.0.4 on 2020-03-19 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200319_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Specifications',
            new_name='specifications',
        ),
    ]
