# Generated by Django 3.0.4 on 2020-04-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200319_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
