# Generated by Django 3.0.4 on 2020-04-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200403_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='str_discount_price',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='str_price',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
