# Generated by Django 3.0.4 on 2020-04-03 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200403_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_discount',
        ),
    ]
