# Generated by Django 3.0.4 on 2020-03-26 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200319_2316'),
        ('orders', '0009_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='productImage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductImage'),
        ),
    ]
