# Generated by Django 3.0.4 on 2020-03-26 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_productinbasket_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='productImage',
        ),
    ]
