# Generated by Django 3.0.4 on 2020-03-29 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_productinbasket_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_phone',
        ),
    ]
