# Generated by Django 3.0.4 on 2020-04-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_order_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, default=None, max_length=48, null=True),
        ),
    ]
