# Generated by Django 3.0.4 on 2020-04-11 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
    ]
