# Generated by Django 3.0.4 on 2020-04-11 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_productinbasket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='user',
        ),
    ]
